### ISSUE TITLE
Implementing Prim algorithm

### ISSUE THREAD

**Issue by CPAlgorithms** [CPAlgorithms/ICPC#13]

**Comment by Ruturaj-7802** [comment]
Please assign me this issue, I want to provide a solution in C++ and if possible then i will also provide a solution in python too @CPAlgorithms

**Comment by Ruturaj-7802** [comment]
Please check PR #21 @CPAlgorithms

**Comment by CPAlgorithms** [comment]
Merged, thanks you ❤
